### ISSUE TITLE
Some error about "outside range"

### ISSUE THREAD

**Issue by AndreaHasani** [ray-x/lsp_signature.nvim#26] opened 2021-06-04 00:35 UTC
Thanks for this plugin, I like it alot (quite useful to do check signature of a method with a shortcut).

When I try to make use of the feature which shows me which argument I need to type, I keep getting this error.

```
Error executing vim.schedule lua callback: ...ck/packer/start/lsp_signature.nvim/lua/lsp_signature.lua:195: end_col value outside range
Error executing vim.schedule lua callback: ...ck/packer/start/lsp_signature.nvim/lua/lsp_signature.lua:195: end_col value outside range
Error executing vim.schedule lua callback: ...ck/packer/start/lsp_signature.nvim/lua/lsp_signature.lua:195: col value outside range
```

Maybe I'm doing something wrong. The language I'm testing this is python with pyright lsp

**Comment by ray-x** [comment] 2021-06-04 00:51
I think there are other reports of this issue and was fixed by updating to latest neovim. Could you verify that?

If issue still existed, Would be great to send out the code snippets and function signature. 

Thanks!

**Comment by vinicius507** [comment] 2021-06-06 23:46
Had the same issue, updating fixed for me :)

**Comment by susiyaki** [comment] 2021-06-20 06:06
Same issue on neovim version `NVIM v0.5.0-dev+1428-g997a9c879`

**Comment by ray-x** [comment] 2021-06-20 11:07
Can you update
1) the lsp server you are using
2) the function signature. Would be great to post the code snippets that can reproduce the issue.

**Comment by susiyaki** [comment] 2021-06-20 11:49
@ray-x 
I'm sorry, and thank you replying

1. nvim-lspconfig
2. 
```:[lua]
local on_attach = function(client, bufnr)
    require'lsp_signature'.on_attach(client)
 
    -- other code: mappings, set option
end

local nvim_lsp = require('lspconfig')
local lsp_install = require('lspinstall')

-- Capabilities
local capabilities = vim.lsp.protocol.make_client_capabilities()

  -- Code actions
  capabilities.textDocument.codeAction = {
      dynamicRegistration = true,
      codeActionLiteralSupport = {
          codeActionKind = {
              valueSet = (function()
                  local res = vim.tbl_values(vim.lsp.protocol.CodeActionKind)
                  table.sort(res)
                  return res
              end)()
          }
      }
  }

  capabilities.textDocument.completion.completionItem.snippetSupport = true;


-- install ls and attach
local langs = {
  "bash",
  "cmake",
  "css",
  "cpp",
  "dockerfile",
  "go",
  "graphql",
  "html",
  "json",
  "lua",
  "python",
  "ruby",
  "rust",
  "tailwindcss",
  "typescript",
  "vim",
  "yaml"
}

local installed_servers = require'lspinstall'.installed_servers()


local function has_server(lang)
  for _, server in pairs(installed_servers) do
    if server == lang then
      return true
    end
  end

  return false
end

for _, lang in pairs(langs) do
  if has_server(lang) == false then
    lsp_install.install_server(lang)
  end
end

local function setup_servers()
  require'lspinstall'.setup()
  for _, server in pairs(installed_servers) do
    nvim_lsp[server].setup{capabilities = capabilities, on_attach = on_attach}
  end
end


setup_servers()

```

**Comment by ray-x** [comment] 2021-06-20 13:20
I think the statement is not correct:
```
require'lsp_signature'.on_attach(client)
```
It should be looks like this:

```
    require "lsp_signature".on_attach({
      bind = true, -- This is mandatory, otherwise border config won't get registered.
      handler_opts = {
        border = "single"
      }
    })
```

I can not tell from your init.lua which language (lsp server) is failed and would be great also post the code (function signature) that caused the failure.  

Thanks!

**Comment by Shatur** [comment] 2021-06-27 09:20
Same here. Happens when a function have several overloads:
![изображение](https://user-images.githubusercontent.com/22453358/123539361-0c5a7400-d742-11eb-8262-2bd4a4283a11.png)

**Comment by ray-x** [comment] 2021-06-27 12:39
Thanks for reporting, The fix for overloads is included in latest version.

**Comment by maxmax1992** [comment] 2021-07-02 08:13
I'm having the same problem, my version is:
```NVIM v0.5.0-dev+1357-g192f89ea1
Build type: RelWithDebInfo```
installed from apt-get, Ubuntu 20.04
Also, I'm using Pyright as LSP with following config (which makes the pyrightconfig.json global for every project)
```
local lspconf = require "lspconfig"
local servers = {"cssls", "pyright"}

for k, lang in pairs(servers) do
    lspconf[lang].setup {
        root_dir = function()
            return vim.loop.cwd()
        end
    }
end

require'lspconfig'.pyright.setup{
    root_dir = function()
        return vim.loop.cwd()
    end
}
require'lspconfig'.bashls.setup{}
require'lspconfig'.clangd.setup{}
require'lspconfig'.vimls.setup{}
```

**Comment by ray-x** [comment] 2021-07-02 08:28
Could you send out the function signature? Thanks!

**Comment by jmattheis** [comment] 2021-07-02 21:23
I've a similar problem 
```
Error executing vim.schedule lua callback: ...ck/packer/start/lsp_signature.nvim/lua/lsp_signature.lua:263: col value outside range
```

Using parentheses inside a function call in rust.
```rust
fn bug(left: i32, rigth: i32) -> i32 {
    return left;
}
fn main() {
    let x = ||42;

    bug(x(), 32)
}
```
![endcol](https://user-images.githubusercontent.com/14895212/124329717-74aeb880-db7b-11eb-9f89-a7c1d31af51f.gif)

**Comment by ray-x** [comment] 2021-07-03 09:01
@jmattheis 
Thanks for sending out the signature and gif. It is helpful!
I submitted a fix for this. Please check.

**Comment by jmattheis** [comment] 2021-07-03 09:08
@ray-x Awesome, it works. Thank you for the quick fix and for maintaining this project (:.

**Comment by darteil** [comment] 2021-07-08 07:55
Same problem (end_col value outside range).

nvim version:
![nvimv](https://user-images.githubusercontent.com/31193144/124883566-a69ca080-dffb-11eb-843a-0e95e8536625.png)

error: 
![out](https://user-images.githubusercontent.com/31193144/124883644-bb793400-dffb-11eb-9469-a238f153dbee.png)

config from on_attach function:
```
local on_attach = function(client, bufnr)
...
  require "lsp_signature".on_attach({
    bind = true,
    hint_prefix = "",
    handler_opts = {
      border = "none",
    }
  })
...
end
```

**Comment by ray-x** [comment] 2021-07-08 08:03
Is it tsserver?

**Comment by darteil** [comment] 2021-07-08 08:05
> Is it tsserver?
Yes

**Comment by ray-x** [comment] 2021-07-08 11:25
@darteil 
Thanks for the info. I think the issue related to function override/multiple-signatures.
The issue should be fixed in the latest version.

**Comment by darteil** [comment] 2021-07-08 11:45
@ray-x
Ок. I will follow the updates. Thanks.

**Closed** 2021-07-27 10:12 UTC
Labels: cannot_reproduce, question
