### ISSUE TITLE
Error on opening ( or start of signature help

### ISSUE THREAD

**Issue by ssmithstone** [ray-x/lsp_signature.nvim#15] opened 2021-05-02 05:16 UTC
Using latest version of neovim HEAD , lastest version of lsp_signature when it gets the signature help on lua/python code i receive the following error

Error executing vim.schedule lua callback: ...utoload/plugged/lsp_signature.nvim/lua/lsp_signature.lua:71: attempt to concatenate local 'hint' (a nil value)

**Comment by ssmithstone** [comment] 2021-05-02 05:23
I had to fill in a config as I was using

on_attach() , the error seems to have gone once I added
on_attach({
            hint_enable = true,
            hint_scheme = "String",
            bind = true,
            handler_opts = {
                border = "single"
            },
            doc_lines = 10
})

**Comment by argapost** [comment] 2021-05-02 07:20
Same here only in lua though, python seems to work.

**Comment by argapost** [comment] 2021-05-02 07:39
In your config can you try:
```lua
	lspsig.on_attach({
			hint_enable = false, -- virtual hint enable
    })

```
and see if that works

**Comment by ssmithstone** [comment] 2021-05-02 08:28
doing that does stop the error however i've noticed now when doing 
```
:messages
```
it says 

```
hover not supported
```

which from reading the source means hover is not in the resolved capabilities of the client but when i check the client capabilities for python hover is in the list

I'm running pyright 1.1.136

and when using lspsaga hover is available

**Comment by argapost** [comment] 2021-05-02 08:30
Yes, I have the same message. Do you use efm alongside pyright? I think it comes from efm.

**Comment by ssmithstone** [comment] 2021-05-02 08:51
No efm installed

**Comment by ray-x** [comment] 2021-05-02 11:25
I did run some simple test with python before push.
<img width="597" alt="Screen Shot 2021-05-02 at 9 23 23 pm" src="https://user-images.githubusercontent.com/1681295/116811446-bb3c6280-ab8c-11eb-9a80-a89f912c55da.png">

Can you guys share with me the python code snips?

**Comment by ray-x** [comment] 2021-05-02 11:32
I know what is wrong. It happened when there is 0 or 1 argument.
A fix was commited.

**Comment by argapost** [comment] 2021-05-02 11:36
Yes, I think it's ok now. Thank you.

**Comment by ray-x** [comment] 2021-05-02 11:37
fixed by ff28cebe9

**Closed by ray-x** 2021-05-02 11:37 UTC

**Comment by argapost** [comment] 2021-05-02 12:01
@ssmithstone  if you find a solution about the `hover not supported` in python can you post it as a comment?

**Comment by ray-x** [comment] 2021-05-02 12:21
I think that is caused by no standard return from pyright. I fixed the issue in latest updates.

**Comment by argapost** [comment] 2021-05-02 12:24
Ah thanks! I thought it wasn't relevant to lsp_signature. Works now perfect!
