### ISSUE TITLE
Error during neovim startup

### ISSUE THREAD

**Issue by milkias17** [ray-x/lsp_signature.nvim#72] opened 2021-08-13 08:44 UTC
On neovim startup lsp_signature gives an error message:
`Error executing vim.schedule lua callback: .../plugged/lsp_signature.nvim/lua/lsp_signature_helper.lua:173: attempt to index global '_NgConfigValues' (a nil value)`

While it still shows signature and works as expected, the error message shows up continuously upon usage. And it isn't specific to any language server.

**Comment by Gelio** [comment] 2021-08-13 09:24
Seems to be a duplicate of https://github.com/ray-x/lsp_signature.nvim/issues/73 reported by me on the same minute :smile:

**Comment by ray-x** [comment] 2021-08-13 10:06
Thanks for reporting.  I used incorrect global var. Should have been fixed.

**Closed** 2021-08-13 10:06 UTC
