### ISSUE TITLE
pyright lsp signature issues

### ISSUE THREAD

**Issue by Trid-collab** [ray-x/lsp_signature.nvim#20] opened 2021-05-31 11:51 UTC
I am trying to set lsp signature for pyright lsp with the latest neovim nightly.  I have noticed it does not automatically popup the signature for the modules like when I do "import pandas as pd" for pandas etc. Also when I try to do  say "pd.read_" the signatures of the method are pretty slow .It only pops up when I press tab and cycle through the list of the autocomplete options and recycle to the top.  Could you please help. I am new to this.

**Comment by ray-x** [comment] 2021-05-31 12:54
Hi, Trid-collab
If the floating window takes too long to popup. It might because of pyright is slow on a large project.  Can you check similar thing still happen for a smaller python project? Also what is your minium config to reproduce the issue:

**Comment by Trid-collab** [comment] 2021-06-01 14:16
I am facing the issue with a small file say with say 5 -10 lines of code

**Comment by Trid-collab** [comment] 2021-06-02 15:55
I ran lua vim.lsp.buf.signature_help() in the command while I had a small python file open. It returned a message "ni"l even though the autocompletes where working. Pardon me if I am sounding like layman, because I am.

**Comment by ray-x** [comment] 2021-06-02 21:14
It is probably  because your cursor not in correct position
e.g:

my_python_function(a, b, c, d)

You will need to put the cursor on either a, b, c or d to trigger signature_help

Also would be great to test
1) my_python_function is a function defined locally in your current source file you are editing
2) my_python_function is a pandas function, e.g `pd.read_`

And see how they works the very first time vim.lsp.buf.signature_help() is called.

**Comment by Trid-collab** [comment] 2021-06-05 16:25
Got it. I now realize what I am looking for. Actually I am trying to migrate from VS Code, which has an option called "editor quicksuggestions" which enables suggestions and signature popups as I keep typing. in python. Is there anyway I could replicate that here

**Comment by ray-x** [comment] 2021-06-05 22:41
https://github.com/hrsh7th/nvim-compe should be something you are looking for which is similar to quicksuggestions

**Comment by Trid-collab** [comment] 2021-06-09 11:10
Ok, let me explain what I was expecting when I said replicating the "editor quicksuggestions" option of  vscode in python . Presently I get continuous autocompletion options as  I type and the module, function along with their description. Say in vs code I type "import pandas as pd" as I type import pan - I start getting the auto completion options starting with "pan" but also the description  of the first highlighting autocomplete option. Today I get the autocomplete options automatically  but the descriptions/signatures don't come up until I press tab. Is there anyway to enable this.

**Comment by ray-x** [comment] 2021-06-09 22:36
That would be impossible for lsp_signature. 
The reason is lsp signature only been triggered automatically when 
1) your cursor is inside a function/method.   e.g. math.fmod(_)       cursor   in `_` position
2) the previous character is either a char that trigger next parameter (e.g. `,`) or an empty space following a trigger char

It is designed to only serve this purpose ATM.  Does it possible to do quick suggestion for module and class? I did not think about it before. But it definitely needs other APIs from lsp to do that.

Maybe you can bring the screen recording to nvim-compe and see how they respond. Maybe they have framework already and can be easy for them.

**Comment by oblitum** [comment] 2021-06-23 20:28
What is being described is preselect feature, and it's not job for signatureHelp providers, it's a completion thing. NeoVim allows this feature, coc.nvim has an option for enabling it, it's off by default to avoid confusion because few language servers provide it. Here's a gif taken from https://github.com/rust-analyzer/rust-analyzer/issues/2037 with side-by-side comparison disabled vs enabled:
![gif-2021-03-16-161620](https://user-images.githubusercontent.com/1269815/111367048-0ea53080-8673-11eb-9365-b5986e9a41a0.gif)

**Comment by ray-x** [comment] 2021-06-23 22:58
Ok, this feature, also a feature for the auto-completion plugin. 
When you type `fmt.Print` The lsp signature is not enabled. As the signature will only be trigger when your cursor is in `fmt.Printf(`,  The reason is lsp server only be activated after a "trigger_character",  the  "trigger_characters" set is provided by lsp server. And as `t` is not in  "trigger_characters" set.  It will not show in this case.

**Comment by oblitum** [comment] 2021-06-26 00:43
nvim-compe does provide always-on preselect, but it's not the default. Possibly this is just a matter of setting that.

**Comment by ray-x** [comment] 2021-06-26 03:54
signature has very specific usage and it should provide function parameter when cursor is inside a function. Preset completion is a feature which design for auto-completion plugin (e.g compe). I have no plan to support preset this ATM.

**Comment by oblitum** [comment] 2021-06-26 06:53
@ray-x hi, for your info, I'm just providing additional context to clarify what feature is it, not that I'm asking lsp_signature.nvim to provide it. OP seems to wish for it, but didn't know the name.

**Comment by ray-x** [comment] 2021-06-26 10:35
Thanks.
As the slowness is more an upstream issue of pyright. I will close this one so I could be more focused on issues of higher priority.

**Closed by ray-x** 2021-06-26 10:35 UTC
